### ISSUE TITLE
Timeout Error after solving captcha

### ISSUE THREAD

**Issue by 41alderson** [AmmeySaini/Edu-Mail-Generator#10]
Tried 2-3 times on widows and ubuntu 20.04 getting same results after solving recaptcha.

Traceback (most recent call last):
  File "bot.py", line 1001, in <module>
    main()
  File "bot.py", line 998, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 395, in start_bot
    WebDriverWait(driver, 60).until(
  File "C:\Users\user123\AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by AmmeySaini** [comment]
this happened with chrome or Firefox ??

**Comment by starlordrs** [comment]
Firefox

**Comment by 41alderson** [comment]
i experienced this with chrome

**Comment by AmmeySaini** [comment]
You might have had clicked next button after after completing captcha which you don't have to
Just fill the captcha and wait for script to continue further dont click any button after completing recaptcha

**Comment by AmmeySaini** [comment]
[https://github.com/AmmeySaini/Edu-Mail-Generator/commit/e090a617c1aa2a7bf0b7b4c0595f45fedde073c4](This) might also fix your issue

**Comment by AmmeySaini** [comment]
[This](https://github.com/AmmeySaini/Edu-Mail-Generator/commit/e090a617c1aa2a7bf0b7b4c0595f45fedde073c4) might also fix the issue

**Comment by 41alderson** [comment]
ok sure will wait for the fix and thanks.
