### ISSUE TITLE
chrome_undetected (For easy captcha) crashes

### ISSUE THREAD

**Issue by transformerking** [AmmeySaini/Edu-Mail-Generator#100]
sry i dont know anything technical about how it works but when i select chrome_undetected (For easy captcha) it and then run bot.py it crashes after i select a college and entered the mail id. Also Please add more colleges

**Comment by AmmeySaini** [comment]
A screenshot or error traceback will be helpful

**Comment by transformerking** [comment]
Its working now sorry for this thread

**Comment by transformerking** [comment]
it works now sorry for this thread.......
