### ISSUE TITLE
A proxy connection has been detected

### ISSUE THREAD

**Issue by keklord1738** [AmmeySaini/Edu-Mail-Generator#101]
![image](https://user-images.githubusercontent.com/88426657/129637192-e0a8a2e5-4851-4e69-a651-96014c913827.png)

**Comment by pedrowzz** [comment]
RT

**Comment by Abhidcruez** [comment]
Same problem

**Comment by Coupdegrace07** [comment]
same

**Comment by JonathanLSignot** [comment]
same

**Comment by MaiSan0010** [comment]
same

**Comment by chahushui** [comment]
**same problem……**

**Comment by AmmeySaini** [comment]
I'm aware of this issue, but due to lack of time I'm not able to research on it as it was fixed earlier, it needs a revised code of incap bypass

I might push an update but NO ETA as of now.
PR's are Welcome

**Comment by TechyKid** [comment]
please  fix it

**Comment by FeelsBadMan1** [comment]
> please fix it

He said 3 days ago he is aware of it, not has much time and he might push a update but no eta. WHy did you tell "please fix it" if he already responsed?

**Comment by pixiboom** [comment]
Gettting proxy error

![image](https://user-images.githubusercontent.com/82303503/133410399-b3526a23-8d55-42e9-8a24-68c0bb6d1f72.png)

**Comment by Mamun-Developer** [comment]
It happens with me doesn't matter if I use a VPN or not. I am not from the USA.

**Comment by adfgdthf** [comment]
please fix it

**Comment by rvr11** [comment]
Hello @AmmeySaini, thanks for your work. Do you have an update on this proxy error?

**Comment by hamham26** [comment]
same error
are we have to use vpn with country you live in? @AmmeySaini

**Comment by palmero334** [comment]
This hasn't been updated in monthssss, when is it gonna get updated? @AmmeySaini

**Comment by 30grand** [comment]
@scamizon I got it updated I paid someone to do it message my telegram

**Comment by palmero334** [comment]
@30grand Can you give me the updated version. I don't have a telegram, maybe you can do it through discord or smth?

**Comment by 30grand** [comment]
https://youtu.be/F5PzK_zIIT4
Here is my video go join the discord in the description

**Comment by palmero334** [comment]
@30grand the discord link no longer works for me, my discord is radioactive_cabinet#3565

**Comment by palmero334** [comment]
@30grand Yea, the discord link is prob expired, can you make a new link?

**Comment by 30grand** [comment]
Try now.

**Comment by palmero334** [comment]
@30grand Joined, your discord username is DARKIE, correct? And also i just realised, are you actually selling the tool?

**Comment by 30grand** [comment]
Message me on discord that’s my name yes

**Comment by Geraldguss** [comment]
Did anyone resolve this by any chance? @AmmeySaini

**Comment by 30grand** [comment]
Ya @everydaylog on telegram
