### ISSUE TITLE
Error 504 Gateway Time-Out, during applying for an applicaiton

### ISSUE THREAD

**Issue by Master-Mind-007** [AmmeySaini/Edu-Mail-Generator#103]
![image](https://user-images.githubusercontent.com/87894877/129951562-2d45f006-d996-4700-9032-d4141ed8f1a6.png)

Got an error 504 Bad Gateway error during applying for Contra Costa College.

**Comment by AmmeySaini** [comment]
That's server end problem
Nothing to be done at our side
