### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Code-KaMyinn** [AmmeySaini/Edu-Mail-Generator#105]
I have successful get email reply from Mt. San Jacinto College!

But to activate the account, I can't go to the login page 
https://login.msjc.edu/_layouts/PG/activate.aspx 

I am facing 403 forbidden
how can I bypass this error ,plz help

**Comment by DraxJaster** [comment]
Use a vpn and you need to connect to the USA/United States. I hope this will fix your problem :)

**Comment by Code-KaMyinn** [comment]
> Use a vpn and you need to connect to the USA/United States. I hope this will fix your problem :)

I have use vpn but still have the same issue 
403 for bitten
Can you go to link 
https://login.msjc.edu/_layouts/PG/activate.aspx
if you can, may be really my fault,
if not, may be the host server 

btw thank you for your reply

**Comment by DraxJaster** [comment]
Which vpn you're using? Make sure the vpn has a california ip
