### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .mypath-confirmation-text

### ISSUE THREAD

**Issue by yashraj22** [AmmeySaini/Edu-Mail-Generator#11]
_____    _         __  __       _ _    ____
| ____|__| |_   _  |  \/  | __ _(_) |  / ___| ___ _ __
|  _| / _` | | | | | |\/| |/ _` | | | | |  _ / _ \ '_ \
| |__| (_| | |_| | | |  | | (_| | | | | |_| |  __/ | | |_
|_____\__,_|\__,_| |_|  |_|\__,_|_|_|  \____|\___|_| |_(_)
      Github Repo - https://git.io/JJisT/

[*] Select a college from all available colleges to proceed....

[*] 1 - MSJC College
[*] 2 - Contra Costa College
[*] 3 - City College
[*] 4 - Sacramento College

[*] Enter college id for ex - 1 or 2 or 3.... : 2

[*] Selected College: Contra Costa College

[*] Enter Your Email: mymail@gmail.com

[*] Hold on Starting now, Keep checking this terminal for instructions
[*] Account Progress - 1/3 (Success)
[*] Account Progress - 2/3 (Success)
[*] Please fill the captcha in webdriver to proceed further
[*] Captcha Solved, Executing Further
[*] Account Progress - 3/3 (Success)
[*] Account Created Successfully, Details saved in myccAcc.txt, Filling Application Form Now
[*] Details Progress - 1/8 (Success)
[*] Details Progress - 2/8 (Success)
[*] Details Progress - 3/8 (Success)
[*] Details Progress - 4/8 (Success)
[*] Details Progress - 5/8 (Success)
[*] Details Progress - 6/8 (Success)
[*] Details Progress - 7/8 (Success)
[*] Details Progress - 8/8 (Success)
[*] Sleeping for 30 seconds, HOLD ON !!
Traceback (most recent call last):
  File "bot.py", line 1001, in <module>
    main()
  File "bot.py", line 998, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 948, in start_bot
    confirmedText = driver.find_element_by_class_name('mypath-confirmation-text').text
  File "/home/yashraj/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "/home/yashraj/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/yashraj/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/yashraj/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .mypath-confirmation-text

**Comment by AmmeySaini** [comment]
Was webdriver window minimized ??

**Comment by yashraj22** [comment]
yeah

**Comment by AmmeySaini** [comment]
[This](https://github.com/AmmeySaini/Edu-Mail-Generator/commit/e090a617c1aa2a7bf0b7b4c0595f45fedde073c4) might fix your issue

**Comment by yashraj22** [comment]
lemme try  , it worked even after that error , I got my edu Thanks
