### ISSUE TITLE
SeleniumWire Module Error

### ISSUE THREAD

**Issue by girlscoutfather** [AmmeySaini/Edu-Mail-Generator#110]
`~/Edu-Mail-Generator/bot.py", line 13, in <module>
    import seleniumwire.undetected_chromedriver.v2 as uc
ModuleNotFoundError: No module named 'seleniumwire.undetected_chromedriver'`

lol u good bro

**Comment by AmmeySaini** [comment]
`python3 -m pip install selenium-wire`

**Comment by girlscoutfather** [comment]
> `python3 -m pip install selenium-wire`

Returned the same error, man.
