### ISSUE TITLE
The bypass is still not working please update it

### ISSUE THREAD

**Issue by Ashutosh1478** [AmmeySaini/Edu-Mail-Generator#124]
![Screenshot from 2021-11-13 10-06-42](https://user-images.githubusercontent.com/79554993/141605808-1c172906-8bab-4c1b-ba48-01095f9ce1f3.png)

**Comment by alexriabtsev** [comment]
confirmed

**Comment by ademisna** [comment]
same case

**Comment by sledgemasterrrr** [comment]
same case

**Comment by jasmine-ejaily** [comment]
same

**Comment by cyberog84** [comment]
How to solve it, want to use VPN for that...?
