### ISSUE TITLE
FIREFOX / CHROME ERRORS

### ISSUE THREAD

**Issue by Alcross008** [AmmeySaini/Edu-Mail-Generator#128]
Hello....I am always getting the following errors even though I have both firefox and chrome installed. Please help. Thanks.
------------------
Firefox
Firefox isn't installed

Chrome
Chrome isn't installed
Error - Setup installation failed
Reason - Please install either Chrome or Firefox browser to complete setup process

**Comment by BangMbon** [comment]
You need to install Firefox or Chrome.

**Comment by Alcross008** [comment]
I have Chrome, Chromium, Firefox, Mozilla Firefox all installed bro. Still
I get the same error.

**Comment by Kuruin** [comment]
any fix?

**Comment by AmmeySaini** [comment]
What OS are you using?

**Comment by Kuruin** [comment]
> What OS are you using?

I fixed it after reboot using arch btw ,and it shows proxy error

**Comment by AmmeySaini** [comment]
Yep, I'm aware of that, kinda busy rn may push fix some other day.

**Comment by 30grand** [comment]
> > What OS are you using?
> 
> I fixed it after reboot using arch btw ,and it shows proxy error

Just switch proxy it works for me @scamizon on telegram

**Comment by iammrhappy** [comment]
Is there a fix for the proxy issue ?
