### ISSUE TITLE
New update when?

### ISSUE THREAD

**Issue by radioactivecabinet** [AmmeySaini/Edu-Mail-Generator#134]
There's a ton of issues now and it needs a new bypass, when is this gonna get updated?

**Comment by AmmeySaini** [comment]
I've more on my hands lately, can't give any ETA, PR's welcome!

**Comment by palmero334** [comment]
@AmmeySaini Kinda sad how some random guy just fixed the issue and trying to sell it for 200$

**Comment by AmmeySaini** [comment]
@palmero334 cool, buy it, and send a PR :)

**Comment by palmero334** [comment]
Haha
