### ISSUE TITLE
"404 - Not Found"

### ISSUE THREAD

**Issue by xhendev** [AmmeySaini/Edu-Mail-Generator#136]
Error when URL "https://account.cccmypath.org/uPortal/p/AccountCreation.ctf1/max/action.uP?pP_execution=e1s1" is opened

**Comment by ENDZHT** [comment]
In China, the website  can`t open. And if using proxy , the site will show the blow image.
![image](https://user-images.githubusercontent.com/37065019/156844120-91e94c15-5221-4b94-ad3c-055f20f82d3d.png)
