### ISSUE TITLE
Hey this works great, just need more info and a error.

### ISSUE THREAD

**Issue by THEG77** [AmmeySaini/Edu-Mail-Generator#14]
So, it  works perfectly fine. No issues whatsoever.
However after openccc account is created and the form is submitted and we get mails.
What's next? i mean is not like they mail you Your Email Password.
If you could add some info on what to do next after receiving mails that would be awesome.

Also I when selecting  "Sacramento College" i get an error:

```
[*] Account Created Successfully, Details saved in myccAcc.txt, Filling Application Form Now
[*] Details Progress - 1/8Traceback (most recent call last):
  File "bot.py", line 1026, in <module>
    main()
  File "bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 445, in start_bot
    dropdown_menu.select_by_index(random.randint(1, 7))
  File "C:\Users\devree\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\support\select.py", line 103, in select_by_index
    raise NoSuchElementException("Could not locate element with index %d" % index)
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with index 7

```

Thanks for this tool.

**Comment by AmmeySaini** [comment]
After getting your application submitted you need to follow instructions sent to you on the mail.
**For Error:**
1. Make sure your webdriver is not minimized as its hard to locate paths and id's of elements
2. Check if you are using latest version of this repo
