### ISSUE TITLE
Error: selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch

### ISSUE THREAD

**Issue by OliveS9** [AmmeySaini/Edu-Mail-Generator#143]
How to fix the error below:

```
...\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
  (Session info: chrome=98.0.4758.102)
Stacktrace:
Backtrace:
       ...
        GetHandleVerifier [0x007EBE02+1675858]
        GetHandleVerifier [0x008A036C+2414524]
        GetHandleVerifier [0x006DBB01+560977]
        GetHandleVerifier [0x006DA8D3+556323]
        Ordinal0 [0x005E020E+2163214]
        Ordinal0 [0x005E5078+2183288]
        Ordinal0 [0x005E51C0+2183616]
        Ordinal0 [0x005EEE1C+2223644]
        BaseThreadInitThunk [0x76456709+25]
        RtlGetFullPathName_UEx [0x77AE7CCD+173]
        RtlGetFullPathName_UEx [0x77AE7C9B+123]
```

when running bot.py? Thanks a lot.

**Comment by dineshattry** [comment]
> How to fix the error below:
> 
> ```
> ...\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidCookieDomainException: Message: invalid cookie domain: Cookie 'domain' mismatch
>   (Session info: chrome=98.0.4758.102)
> Stacktrace:
> Backtrace:
>        ...
>         GetHandleVerifier [0x007EBE02+1675858]
>         GetHandleVerifier [0x008A036C+2414524]
>         GetHandleVerifier [0x006DBB01+560977]
>         GetHandleVerifier [0x006DA8D3+556323]
>         Ordinal0 [0x005E020E+2163214]
>         Ordinal0 [0x005E5078+2183288]
>         Ordinal0 [0x005E51C0+2183616]
>         Ordinal0 [0x005EEE1C+2223644]
>         BaseThreadInitThunk [0x76456709+25]
>         RtlGetFullPathName_UEx [0x77AE7CCD+173]
>         RtlGetFullPathName_UEx [0x77AE7C9B+123]
> ```
> 
> when running bot.py? Thanks a lot.

hi is your error is fix ?

**Comment by OliveS9** [comment]
@dineshattry   No, it has not been fixed. Can you please fix the error? Thanks.
