### ISSUE TITLE
Connection aborted

### ISSUE THREAD

**Issue by ENDZHT** [AmmeySaini/Edu-Mail-Generator#145]
When I use proxy and run bot.py, it show the error, "Error - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
"
![image](https://user-images.githubusercontent.com/37065019/156830284-8b47d052-2528-47f0-8fd7-ed22fc39e4c5.png)

**Comment by ENDZHT** [comment]
close the proxy, and run script

**Comment by shoyrock** [comment]
> close the proxy, and run script

did you ever get it to work?

**Comment by ENDZHT** [comment]
> > close the proxy, and run script
> 
> did you ever get it to work?

No, I tried my best

**Comment by shoyrock** [comment]
> > > close the proxy, and run script
> > 
> > 
> > did you ever get it to work?
> 
> No, I tried my best

Thanks got the reply, I tried paying someone to fix it for more but no wanted the job idk why
