### ISSUE TITLE
I want an edu email and who can help me

### ISSUE THREAD

**Issue by ENDZHT** [AmmeySaini/Edu-Mail-Generator#146]
I don`t access the website "https://www.openccc.net/", but I really need an edu email. Please help me apply for an edu email to me.
Call me by ENDZHT@outlook.com

**Comment by shoyrock** [comment]
> I don`t access the website "https://www.openccc.net/", but I really need an edu email. Please help me apply for an edu email to me. Call me by [ENDZHT@outlook.com](mailto:ENDZHT@outlook.com)

https://klineaccounts.com/#accounts

**Comment by peaky1357** [comment]
> > I don`t access the website "https://www.openccc.net/", but I really need an edu email. Please help me apply for an edu email to me. Call me by [ENDZHT@outlook.com](mailto:ENDZHT@outlook.com)
> 
> https://klineaccounts.com/#accounts

What if I have no money

**Comment by shoyrock** [comment]
> > > I don`t access the website "https://www.openccc.net/", but I really need an edu email. Please help me apply for an edu email to me. Call me by [ENDZHT@outlook.com](mailto:ENDZHT@outlook.com)
> > 
> > 
> > https://klineaccounts.com/#accounts
> 
> What if I have no money

Sorry but you’re out of luck as of right now
