### ISSUE TITLE
nft upload error

### ISSUE THREAD

**Issue by dineshattry** [AmmeySaini/Edu-Mail-Generator#147]
raise timeoutexception(message screen stacktrace) selenium.common.exceptions.timeoutexception

how can i fix it

**Comment by dineshattry** [comment]
![Screenshot (111)](https://user-images.githubusercontent.com/101259183/157437814-32611ed5-7469-4572-a87a-aa88e2670eb5.png)

**Comment by dineshattry** [comment]
![Screenshot (111)](https://user-images.githubusercontent.com/101259183/157437954-8042f69d-3cc0-4044-96c2-a2b7f95115e7.png)
 how can i solve this

**Comment by dineshattry** [comment]
pls help me....

**Comment by dineshattry** [comment]
> Message that will be displayed on users first issue

how can i fix it
pls help

**Comment by rohit746** [comment]
Yes, I have the same error. Please help!
