### ISSUE TITLE
Fix to this Error? "Message: invalid cookie domain: Cookie 'domain' mismatch"

### ISSUE THREAD

**Issue by Bluecyke** [AmmeySaini/Edu-Mail-Generator#150]
Hi All -

Basically Chrome window opens and then closes after inputting my email address (please see attached screenshot).

I already disabled some flag options in chrome.  Anyone can help me please?  Thank you.

![edu](https://user-images.githubusercontent.com/26081881/161169201-bf3d5389-a6b6-40c9-b1be-1be99c151af3.PNG)

This is the tab that opens, and then automatically closes
![edu2](https://user-images.githubusercontent.com/26081881/161171509-052f62ef-7b7f-467d-9fd4-1f35d6b6bee4.PNG)

This is what I get in the cmd screen before automatically closing...
![edu3](https://user-images.githubusercontent.com/26081881/161171556-53039f6c-63c0-4f23-b566-aed17eaca5ce.PNG)

**Comment by Bluecyke** [comment]
Message: invalid cookie domain: Cookie 'domain' mismatch 
(Session info: chrome=##.#.####.##)

**Comment by 30grand** [comment]
bruh dm me telegram @scamizon
