### ISSUE TITLE
It's not Working (See Code for More Info)

### ISSUE THREAD

**Issue by FrozenCoder1** [AmmeySaini/Edu-Mail-Generator#16]
`_____    _         __  __       _ _    ____
| ____|__| |_   _  |  \/  | __ _(_) |  / ___| ___ _ __
|  _| / _` | | | | | |\/| |/ _` | | | | |  _ / _ \ '_ \
| |__| (_| | |_| | | |  | | (_| | | | | |_| |  __/ | | |_
|_____\__,_|\__,_| |_|  |_|\__,_|_|_|  \____|\___|_| |_(_)
      Github Repo - https://git.io/JJisT/

[*] Select a college from all available colleges to proceed....

[*] 1 - MSJC College
[*] 2 - Contra Costa College
[*] 3 - City College
[*] 4 - Sacramento College

[*] Enter college id for ex - 1 or 2 or 3.... : 4

[*] Selected College: Sacramento College

[*] Enter Your Email: ilovemusic.frozen@gmail.com

[*] Hold on Starting now, Keep checking this terminal for instructions

DevTools listening on ws://127.0.0.1:64413/devtools/browser/e072962d-0cee-42ae-9f52-348e27405af9
[5524:11540:0826/140348.239:ERROR:device_event_log_impl.cc(208)] [14:03:48.238] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.
[*] Account Progress - 1/3 (Success)
[*] Account Progress - 2/3 (Success)
[*] Please fill the captcha in webdriver to proceed further
[*] Captcha Solved, Executing Further
[*] Account Progress - 3/3 (Success)
[*] Account Created Successfully, Details saved in myccAcc.txt, Filling Application Form Now
[*] Details Progress - 1/8 (Success)
[*] Details Progress - 2/8 (Success)
[*] Details Progress - 3/8 (Success)
[*] Details Progress - 4/8 (Success)
[*] Details Progress - 5/8Traceback (most recent call last):
  File "bot.py", line 1026, in <module>
    main()
  File "bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "bot.py", line 671, in start_bot
    WebDriverWait(driver, 60).until(
  File "site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
  File "site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
  File "site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
  File "site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <input id="inputFinAidInfoNo" name="_appNeedsAndInterestsForm.financialAidInfo" class="portlet-form-input-radio" type="radio" value="false"> is not clickable at point (161, 6). Other element would receive the click: <img src="/gateway/logos/logo.sacramento-city.png" alt="Sacramento City College">
  (Session info: chrome=84.0.4147.135)

[2972] Failed to execute script bot`

**Comment by AmmeySaini** [comment]
You should make sure you don't minimize the webdriver for long as it's hard to find keys and paths in minimized driver.
I had also added code to make it work with minimized which worked absolutely fine for me so make sure you have latest version of this repo
