### ISSUE TITLE
Vpn/proxy error

### ISSUE THREAD

**Issue by NukeVsScript** [AmmeySaini/Edu-Mail-Generator#164]
Yep

**Comment by FuckingToasters** [comment]
Take a look at the last response from me in this issue: #83 
A few Code changes are required for it to work again. Also you always should look in closed issues if anyone have the same issue and if it's solved there before you create a new issue.

**Comment by Md-MamunMia** [comment]
Anonymizing browser plugins issue. I didn't know. This website (Host: www.opencccapply.net) banned my IP. Is there any other way to get rid of this problem?
