### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by noonegupta734** [AmmeySaini/Edu-Mail-Generator#17]
Hi Your repo is very good can u add more college i know i am asking too much but if you could add more colleges it would help a lot as these colleges will stop accepting application due to many applications

**Comment by AmmeySaini** [comment]
yes i might add new colleges soon but as for now i have some work on hands

**Comment by noonegupta734** [comment]
Ok Thanks 👍

**Comment by usmanmughalji** [comment]
@AmmeySaini  Request: Please add this college too: https://www.dvc.edu/future/steps/index.html

**Comment by noonegupta734** [comment]
Is this college still giving edu
