### ISSUE TITLE
Error while running it

### ISSUE THREAD

**Issue by jayjani007** [AmmeySaini/Edu-Mail-Generator#170]
Hi
I am getting an error while running `sudo python3 bot.py`

<img width="636" alt="2023-07-31 13_13_43-" src="https://github.com/AmmeySaini/Edu-Mail-Generator/assets/20972659/f15cb229-536d-4430-94b6-d28f378904ed">

**Comment by ZlashBoi** [comment]
Same did anyone figure out if there is a solution?
