### ISSUE TITLE
option to add other colleges working with OpenCCC

### ISSUE THREAD

**Issue by togoti3150** [AmmeySaini/Edu-Mail-Generator#20]
I would like to add other colleges working with openccc if possible

**Comment by togoti3150** [comment]
Never mind if found it.

**Comment by TheFatalKiller** [comment]
> Never mind if found it.

What did you do?

**Comment by togoti3150** [comment]
edited https://github.com/AmmeySaini/Edu-Mail-Generator/blob/master/__constants/const.py
