### ISSUE TITLE
Fail running main python file

### ISSUE THREAD

**Issue by aibtiy** [AmmeySaini/Edu-Mail-Generator#21]
There is im got an notice are wrong to do. This is print:
Error - Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Note: when i was start setup at first moment i got screen not have been installed chrome or firefox. and after run at 2nd moment it i to run main python file

**Comment by AmmeySaini** [comment]
check this #8
