### ISSUE TITLE
Fix it

### ISSUE THREAD

**Issue by Hunter11821** [AmmeySaini/Edu-Mail-Generator#29]
I seen this error all time
I already install chrome/Firefox browser

![Screenshot_2020-11-13-13-17-14-389_com termux](https://user-images.githubusercontent.com/68858839/99042992-ae628d00-25b3-11eb-9531-94ea11d79d77.jpg)

**Comment by AmmeySaini** [comment]
Are you using termux ?

**Comment by Hunter11821** [comment]
Yes I am using termux can you ask me which tool is best for it. I mean
pc/termux/kali. if you using telegram plz contact me @Official_Hunter it's
my telegram username

શુક્ર, 13 નવે, 2020 1:33 PM ના રોજ Ammey Saini <notifications@github.com>એ
લખ્યું:

**Comment by AmmeySaini** [comment]
We don't support termux and no development will be done for the same.
Better use linux/win
