### ISSUE TITLE
The bot can't open Firefox

### ISSUE THREAD

**Issue by rad275** [AmmeySaini/Edu-Mail-Generator#30]
I enter this info in the Command-Line and after I press the final enter confirmation the firefox doesn't open.
This is the bot Program Screen Shot: https://prnt.sc/vkj3n7
I've installed all the requirements and I don't know what to the further. PLS HELP
This is the "setup" Program ScreenShot: https://prnt.sc/vkj6q6

Edit:
How should I set my pref Browser

**Comment by AmmeySaini** [comment]
After downloading all the drivers using setup.py it asks for your preffered browser you might have missed the same step.
You can try running setup again and complete all steps until it shows setup complete.

**Comment by rad275** [comment]
how should I set my prefBrowser

**Comment by rad275** [comment]
> After downloading all the drivers using setup.py it asks for your preffered browser you might have missed the same step.
> You can try running setup again and complete all steps until it shows setup complete.

The setup.py closes immediately after it completes the downloading process, I don't know how should I manage this.

**Comment by AmmeySaini** [comment]
Make sure you arr using latest version of this repo.
For setting firefox as your preffered browser just open
`prefBrowser.txt and write 0 in it and save`
