### ISSUE TITLE
Error on setup.py 

### ISSUE THREAD

**Issue by vaodaa** [AmmeySaini/Edu-Mail-Generator#31]
![Capture](https://user-images.githubusercontent.com/59312266/99991697-a70e6100-2db5-11eb-82de-6d6a7157a66e.PNG)
Why pls ?

**Comment by AmmeySaini** [comment]
Seems like you are using some sniffing software/tool exit it and run setup again

**Comment by AmmeySaini** [comment]
You can close this now if it's fixed

**Comment by camlogical** [comment]
> ![Capture](https://user-images.githubusercontent.com/59312266/99991697-a70e6100-2db5-11eb-82de-6d6a7157a66e.PNG)
> Why pls ?

You tried to hide your name but it still shown "ZOUH". To fix this error Please Update the webdriver to compatible with your browser.
