### ISSUE TITLE
  raise TimeoutException(message, screen, stacktrace) selenium.common.exceptions.TimeoutException: Message:

### ISSUE THREAD

**Issue by ReubenAboagye** [AmmeySaini/Edu-Mail-Generator#35]
Traceback (most recent call last):
  File "C:\Users\reube\Desktop\Edu-Mail-Generator-master\bot.py", line 1026, in <module>
    main()
  File "C:\Users\reube\Desktop\Edu-Mail-Generator-master\bot.py", line 1023, in main
    start_bot(reg_url, userEmail, allColleges[userInput], userInput + 1)
  File "C:\Users\reube\Desktop\Edu-Mail-Generator-master\bot.py", line 513, in start_bot
    WebDriverWait(driver, 60).until(
  File "C:\Users\reube\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

bot stops working after this shows.

**Comment by AmmeySaini** [comment]
Don't minimize webdriver

**Comment by ReubenAboagye** [comment]
![wevb](https://user-images.githubusercontent.com/62930308/101992178-36b67980-3ca9-11eb-907a-3442ef78b8f9.png)
this is where the bot stops



and this is what I see in the bot.py terminal after 2 mins when the bot stops.
![termimal](https://user-images.githubusercontent.com/62930308/101992192-52218480-3ca9-11eb-9bbf-c73d129591f1.png)

**Comment by AmmeySaini** [comment]
This usually happens when bot can't locate a specific button location so, possibility can either u did minimized the webdriver or changed it's size.
Have you tried again without clicking anywhere when the bot starts. If not just try it once again and let the bot do rest of the work don't click anywhere and main thing don't minimize it.

**Comment by ReubenAboagye** [comment]
I only did the captcha. after the captcha I don''t click anywhere else

**Comment by AmmeySaini** [comment]
Okay then let me know what college you choose and what browser (firefox or chorme).
Try providing me all the details
I'll try replicating the same error.

**Comment by ReubenAboagye** [comment]
I used both Firefox and chrome. I also tried all the colleges

**Comment by Ahlyab** [comment]
@AmmeySaini Sir kindly fix it 
facing same issue

**Comment by chandeepadissanayake** [comment]
@AmmeySaini Happens to me too. 
![image](https://user-images.githubusercontent.com/13079067/102536061-13d3fd00-40cf-11eb-84c4-20334df5ea51.png)

**Comment by AmmeySaini** [comment]
I'm aware of this issue. I might push an update for it soon.

**Comment by chandeepadissanayake** [comment]
For a quick fix, you can replace the line no 513,514,515 by the following lines in bot.py

`dropdown_menu_1 = Select(driver.find_element_by_name('appEducation.hsAttendance'))
        dropdown_menu_1.select_by_index(1)`

Hope this might help @Anmolfid1 @Ahlyab 

@AmmeySaini  I can come up with a pull request if I have enough time.

**Comment by iyantae245** [comment]
> For a quick fix, you can replace the line no 513,514,515 by the following lines in bot.py
> 
> `dropdown_menu_1 = Select(driver.find_element_by_name('appEducation.hsAttendance')) dropdown_menu_1.select_by_index(1)`
> 
> Hope this might help @Anmolfid1 @Ahlyab
> 
> @AmmeySaini I can come up with a pull request if I have enough time.

dude, you save my day it works.. thank you so much 

![unknown](https://user-images.githubusercontent.com/30578879/102956082-6d468c80-4512-11eb-9212-b07b48d3b6c6.png)

**Comment by ReubenAboagye** [comment]
@chandeepadissanayake thank you so much for the quick fix. 👍🙌

**Comment by AmmeySaini** [comment]
Fixed!! Ref - [here](https://github.com/AmmeySaini/Edu-Mail-Generator/commit/a18d3929eea47297b2a4e968ed022f4d6a9948cb)
