### ISSUE TITLE
I get this error while running (Error - Message: Service ./webdriver/geckodriver unexpectedly exited. Status code was: -7)

### ISSUE THREAD

**Issue by raheemmuizz** [AmmeySaini/Edu-Mail-Generator#36]
After running setup.py to install the script I selected firefox browser because the script wasn't able to detect chrome browser on my kali machine, I guess that might be due to my chrome installation method, so when I run the script for firefox browser I get this error:
@localhost:~/Edu-Mail-Generator$ python3 bot.py       
 _____    _         __  __       _ _    ____
| ____|__| |_   _  |  \/  | __ _(_) |  / ___| ___ _ __
|  _| / _` | | | | | |\/| |/ _` | | | | |  _ / _ \ '_ \
| |__| (_| | |_| | | |  | | (_| | | | | |_| |  __/ | | |_
|_____\__,_|\__,_| |_|  |_|\__,_|_|_|  \____|\___|_| |_(_)
      Github Repo - https://git.io/JJisT/

[*] Select a college from all available colleges to proceed....

[*] 1 - MSJC College
[*] 2 - Contra Costa College
[*] 3 - City College
[*] 4 - Sacramento College

[*] Enter college id for ex - 1 or 2 or 3.... : 2

[*] Selected College: Contra Costa College

[*] Enter Your Email: blabla@gmail.com

[*] Hold on Starting now, Keep checking this terminal for instructions

Error - Message: Service ./webdriver/geckodriver unexpectedly exited. Status code was: -7

User@localhost:~/Edu-Mail-Generator$

**Comment by AmmeySaini** [comment]
What OS you are trying on ?

**Comment by raheemmuizz** [comment]
Kali linux

**Comment by thainb** [comment]
can you fix this i have tried this 0.26 but running n image validation failed

**Comment by Udyz** [comment]
have u install chrome or firefox?

**Comment by AmmeySaini** [comment]
Seems like you have done something wrong with setup
Try doing it again
