### ISSUE TITLE
can't validate captcha

### ISSUE THREAD

**Issue by thainb** [AmmeySaini/Edu-Mail-Generator#39]
Hope you fix it soon, I thank you
![lỗi](https://user-images.githubusercontent.com/76728331/103273527-177e5280-49f2-11eb-8d47-019d640f3b07.png)

**Comment by AmmeySaini** [comment]
You have to verify captcha manually

**Comment by thainb** [comment]
I did the captcha manually but then the version doesn't work anymore

**Comment by thainb** [comment]
When do you release the 0.27 version, I hope you do it soon. Thank you very much

**Comment by AmmeySaini** [comment]
What do you mean version by doesn't work anymore ?

**Comment by Udyz** [comment]
![image](https://user-images.githubusercontent.com/39673284/103396751-7c0eee00-4b67-11eb-896b-254a3125f8ed.png)
have you use 2captcha

**Comment by thainb** [comment]
How do you use 2captcha?  I use chrome

**Comment by manashan** [comment]
> ![image](https://user-images.githubusercontent.com/39673284/103396751-7c0eee00-4b67-11eb-896b-254a3125f8ed.png)
> have you use 2captcha

how did you implemented 2captcha? and how do you bypass the error says proxy,vpn,tor
