### ISSUE TITLE
How to bypass this?

### ISSUE THREAD

**Issue by manashan** [AmmeySaini/Edu-Mail-Generator#41]
![Screenshot_1](https://user-images.githubusercontent.com/67643821/104104897-c9076880-52bb-11eb-88cd-784841fac16b.png)

**Comment by AmmeySaini** [comment]
Use some good quality vpn's

**Comment by manashan** [comment]
I see, I am a new user of this script.
Can you tell me which schools are faster to accepted and get the email?
