### ISSUE TITLE
Sugestion - more automation

### ISSUE THREAD

**Issue by drawix** [AmmeySaini/Edu-Mail-Generator#43]
Hello, is there any possiblity you could add some auto-captcha such as 2captcha feature? Also mail list in .txt would be nice.
This would create fully automated script.

PS. Great script, thanks for your work!

**Comment by VladPutinEu** [comment]
@drawix 2captcha costs money which isn't feasible for a free open-source project. @AmmeySaini would be better off using something like [nonoCAPTCHA](https://github.com/mikeyy/nonoCAPTCHA).
