### ISSUE TITLE
Where's the email? (Please don't close)

### ISSUE THREAD

**Issue by VladPutinEu** [AmmeySaini/Edu-Mail-Generator#54]
@AmmeySaini I successfully completed setup, but where is my .edu email. I used Contra Costa College. Does my application have to be approved for me to get my email? How am I supposed to get the email. I know you've closed issues like this in the past but please don't close this one. Please, I'm just trying to get an .edu email.

**Comment by f4ku123** [comment]
inside myccAcc.txt in the folder of the script

**Comment by VladPutinEu** [comment]
> inside myccAcc.txt in the folder of the script

That gives me information like the full name, birth date, pin, and password. But I can't find the .edu email anywhere.

**Comment by f4ku123** [comment]
> 
> 
> > inside myccAcc.txt in the folder of the script
> 
> That gives me information like the full name, birth date, pin, and password. But I can't find the .edu email anywhere.

Don't waste your time, doesn't work.. i guess they've patched it.

**Comment by VladPutinEu** [comment]
> > > inside myccAcc.txt in the folder of the script
> > 
> > 
> > That gives me information like the full name, birth date, pin, and password. But I can't find the .edu email anywhere.
> 
> Don't waste your time, doesn't work.. i guess they've patched it.

Yeah, that's what I thought. Thanks, that was the answer I was looking for.
