### ISSUE TITLE
TimeoutException(message, screen, stacktrace) selenium.common.exceptions.TimeoutException: Message: 

### ISSUE THREAD

**Issue by basheerkafaf** [AmmeySaini/Edu-Mail-Generator#60]
I am getting this error with the below code, I tried CHrome and FIrefox same thing.

Traceback (most recent call last):
  File "C:/python/bot_test/fast_buy_FF.py", line 56, in <module>
    checkout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "turbo-checkout-pyo-button")))
  File "C:\Users\basheer.kafaf\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
![Snag_2fd63c2](https://user-images.githubusercontent.com/61880491/109758950-85d5c180-7ba9-11eb-8a79-044d360ea853.png)
![Snag_2fdf6ab](https://user-images.githubusercontent.com/61880491/109759002-9c7c1880-7ba9-11eb-8dbd-2112cdba6fa1.png)

Code:

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
driver = webdriver.Firefox()

Max_price = 20000

Item_code = 'B08N5D31XF'
Item_http_offer_page = 'https://www.amazon.com/dp/{}?smid=ATVPDKIKX0DER&tag=data20-20#aod'.format(Item_code)
Item_http_Product_page = 'https://www.amazon.com/gp/product/{}?tag=ns0ec-20'.format(Item_code)

log_in_email = "XXXXXXXXXXXXX"
passward = "XXXXXXXXXX"
driver.get("https://www.amazon.com/ref=nav_logo")

sgin_in = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "nav-signin-tooltip")))
sgin_in.click()

ap_email = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.ID, "ap_email")))
ap_email.send_keys(log_in_email)
search1 = driver.find_element_by_id("continue")
search1.click()

ap_password = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.ID, "ap_password")))
ap_password.send_keys(passward)
search2 = driver.find_element_by_id("signInSubmit")
search2.click()

time.sleep(1)
New_tab = driver.find_element_by_tag_name('body').send_keys(Keys.CONTROL + 't')
driver.get(Item_http_Product_page)

Looper = True

while Looper:
    # try:
        buybox = WebDriverWait(driver, 2).until(EC.presence_of_element_located((By.ID, "price_inside_buybox")))
        print (buybox.text)
        item_price = int(float(buybox.text.replace(',', '').replace('$','')))
        print (item_price)

        if  item_price < Max_price:
            # playsound('bells.mp3')
            buy_now= WebDriverWait(driver, 4).until(EC.presence_of_element_located((By.ID, "buy-now-button")))
            buy_now.click()
            checkout = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "turbo-checkout-pyo-button")))
            checkout.click()
            Looper = False

        time.sleep(5)
        driver.refresh()

    # except:
    #     print('No buy now available yet ')
    #     time.sleep(1)
    #     driver.refresh()

**Comment by AmmeySaini** [comment]
Seems like you are lost 😅
