### ISSUE TITLE
Registered successfully but address error

### ISSUE THREAD

**Issue by StrikerOne65** [AmmeySaini/Edu-Mail-Generator#64]
Registered successfully but address error. It is asking for address confirmation in email.

**Comment by Scui1** [comment]
> 
> 
> Registered successfully but address error. It is asking for address confirmation in email.

same for me, have you found any fix yet?

**Comment by StrikerOne65** [comment]
> > Registered successfully but address error. It is asking for address confirmation in email.
> 
> same for me, have you found any fix yet?

nope

**Comment by StrikerOne65** [comment]
Why invalid???
