### ISSUE TITLE
Myacc.txt doesnt save Login details

### ISSUE THREAD

**Issue by nischaysinha2208** [AmmeySaini/Edu-Mail-Generator#68]
![image](https://user-images.githubusercontent.com/83533057/116806875-8230cd80-ab4d-11eb-8bbd-316cbac13c94.png)

it says Account Created Successfully, Details saved in myccAcc.txt but when i checked the txt files its empty please fix it
HUMBLe REQUEST

**Comment by AmmeySaini** [comment]
Make sure you provide proper permissions to myacc.txt file

**Comment by nischaysinha2208** [comment]
How can i do this please explain

**Comment by AmmeySaini** [comment]
Check permissions of the file in properties

**Comment by nischaysinha2208** [comment]
Oh what permissons should be given

**Comment by AmmeySaini** [comment]
It should be read and write

**Comment by nischaysinha2208** [comment]
![1619946659807632598942](https://user-images.githubusercontent.com/83533057/116808061-74cb1180-ab54-11eb-8415-502fcd3bc67e.jpg)
I checked and unticked the read only  

Anything else i need to do

**Comment by AmmeySaini** [comment]
Check some YouTube video for this

**Comment by nischaysinha2208** [comment]
![image](https://user-images.githubusercontent.com/83533057/116809923-671a8980-ab5e-11eb-999e-187c98d543b4.png)
TRIED MANY THINGS DID LOT OF GOOGLE SEARCHS STILL NOT FIXED it doesnt save any login details in my cc acc tried in diffrent colleges and it doesnt even save prefer browser i check but however it remebers what browser i prefer 


please man help take your 2 min of life and make me happy humble request
