### ISSUE TITLE
Address error

### ISSUE THREAD

**Issue by hilfing** [AmmeySaini/Edu-Mail-Generator#74]
After applying i receive a mail from the college asking me to verify my address. What to do?
Pls dont close this

**Comment by AnweshPaila** [comment]
Please fix this issue

**Comment by hilfing** [comment]
pls fix this

**Comment by hilfing** [comment]
Why are you closing this

**Comment by hilfing** [comment]
This is an error cause the bot fails the email check

**Comment by hilfing** [comment]
FIX THIS

**Comment by AmmeySaini** [comment]
There is no problem with the bot, it's the college doing the formalities which cannot be controlled by our end.

**Comment by hilfing** [comment]
Then, what to do. how do i bypass it
