### ISSUE TITLE
No proper permission to chrome driver in Ubuntu.  

### ISSUE THREAD

**Issue by Aditya7861** [AmmeySaini/Edu-Mail-Generator#8]
I got an error on the first run 
`_Error - Message: 'chromedriver' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home
_`
I have to find chrome drive folder manually and given proper permission.you can handle this with your code .

**Comment by AmmeySaini** [comment]
you have to give permissions (0777) manually to geckodriver and chromedriver files

check ./webdriver/geckodriver ./webdriver/chromedriver go to properties and give 0777 as permission
it'll work after that
