### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\jayes\Downloads\Edu-Mail-Generator-bdca5cecffa957fb475577cd0fa4f8462ca46094\bot.py", line 6, in <module>     import colorama ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by rokyj20211** [AmmeySaini/Edu-Mail-Generator#80]
Traceback (most recent call last):
  File "C:\Users\jayes\Downloads\Edu-Mail-Generator-bdca5cecffa957fb475577cd0fa4f8462ca46094\bot.py", line 6, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'

**Comment by AmmeySaini** [comment]
You need to run setup before trying to run the bot
Still if you get the error after running setup use `python3 -m pip install colorama`

**Comment by rokyj20211** [comment]
Can you please send me education email you have genaratored.With the
password. Please.

**Comment by rokyj20211** [comment]
Thanks, I'll check it out.
