### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by aks-glitch** [AmmeySaini/Edu-Mail-Generator#81]
I dont have pc 
So i tried termux
Everything working fine but problem is in browser checking 
It says install chrome either firefox
Maybe because arch is not supported
Please make this to work on android also 
🙏🙏

**Comment by AmmeySaini** [comment]
We won't be supporting android any time soon!!

**Comment by aks-glitch** [comment]
> We won't be supporting android any time soon!!

Then im not able to generate it 
What's problem with android please try to help
Or give me any edu mail that i can use
My gmail - bhanbhullar@gmail.com
