### ISSUE TITLE
Stuck at error run setup.py first

### ISSUE THREAD

**Issue by aks-glitch** [AmmeySaini/Edu-Mail-Generator#82]
I am usimg kali nethunter
Required packages are install
Script instll firefox drivers also
But when i do bot.py it stuck after i type my email
It says do run stup first even i did 2 times
Help me

**Comment by AmmeySaini** [comment]
Can you check what permissions the folder is having where you cloned the repo

**Comment by Micah-J07** [comment]
I'm having a similar issue - I'm on Ubuntu and can't install dependencies and I'm also unable to run setup.py. Any commands I need to run or is it just in the wrong folder as it did say that it couldn't locate the directory?

**Comment by AmmeySaini** [comment]
It'll be better if you can show the screenshot of the error

**Comment by Edurn** [comment]
I found the solution, open prefBrowser.txt and put your prefered browser chrome or firefox and the problem will be fixed
