### ISSUE TITLE
Proxy detected

### ISSUE THREAD

**Issue by ManasvinYadav** [AmmeySaini/Edu-Mail-Generator#85]
its still showing proxy detected after using chrome undected and can someone tell why when i press cntrl shift n then it opens a icognito and paste link there but it still doesnt work pls help

**Comment by K-281** [comment]
it's because they use incapsula as CDN security provider, could be working again with https://github.com/ziplokk1/incapsula-cracker-py3

**Comment by K-281** [comment]
> 
> 
> it's because they use incapsula as CDN security provider, could be working again with https://github.com/ziplokk1/incapsula-cracker-py3

![2021-07-26 11_44_05-https___www openccc net_cccacct-proxy_createAccount_locale=en source=https___www](https://user-images.githubusercontent.com/48651626/126968990-b2c28a5a-84b1-4638-a7c1-54ea960ba234.jpg)

**Comment by Thenafi** [comment]
Faceing same issue

**Comment by AmmeySaini** [comment]
#83
