### ISSUE TITLE
Stuck On Account Progress 3

### ISSUE THREAD

**Issue by Thenafi** [AmmeySaini/Edu-Mail-Generator#86]
![image](https://user-images.githubusercontent.com/65831153/127903267-b125571b-58ed-4c88-88d6-f8164cfb9973.png)

is it just me ? . I am using vpn here.. because i live in asia

**Comment by FeelsBadMan1** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/65831153/127903267-b125571b-58ed-4c88-88d6-f8164cfb9973.png)
> 
> is it just me ? . I am using vpn here.. because i live in asia

I had the same issure without using a VPN. You could try to use the new updated Files in this repo and somehow the sites blocked my IP so i couldnt reach these Websites even without the bot using the usual browser. i then used a virtual creditcard and registerd a amazon aws account. using a windowsrdp now and it works fine there.

**Comment by Thenafi** [comment]
> > ![image](https://user-images.githubusercontent.com/65831153/127903267-b125571b-58ed-4c88-88d6-f8164cfb9973.png)
> > is it just me ? . I am using vpn here.. because i live in asia
> 
> I had the same issure without using a VPN. You could try to use the new updated Files in this repo and somehow the sites blocked my IP so i couldnt reach these Websites even without the bot using the usual browser. i then used a virtual creditcard and registerd a amazon aws account. using a windowsrdp now and it works fine there.

i used the updated repo.. i tried it afteer the latest update .........
