### ISSUE TITLE
[Suggestion] use Emails from a file

### ISSUE THREAD

**Issue by FeelsBadMan1** [AmmeySaini/Edu-Mail-Generator#89]
Allow us to set emails in a file that the tool then choose from. 
These sites allow us to use google dottrick so there are some Websites that create a list of emails with random dots into them and it would be better if you could save them to a file called emails.txt and then the tool use a email, if its done it remove the email from the file and after closing the browser it directly continues with another process etc.

**Comment by AmmeySaini** [comment]
The project was not made for spamming the services, hence won't be working on this :)
