### ISSUE TITLE
Still showing proxy error and some other errors

### ISSUE THREAD

**Issue by p32929** [AmmeySaini/Edu-Mail-Generator#90]
Hello, Thanks for making this script. Today I wanted to try this ( v0.2.8 ) and encountered these errors:

![Screenshot (80)](https://user-images.githubusercontent.com/6418354/127985326-bdf7d8c9-02de-4f6f-9b60-ea694644c49d.png)

![Screenshot (81)](https://user-images.githubusercontent.com/6418354/127985412-42ffa5f0-ca97-4279-aba8-8d3d245d5643.png)

![Screenshot (82)](https://user-images.githubusercontent.com/6418354/127985420-52cedbe0-b50d-416d-9c7a-31e6fe8420d6.png)

While doing the setup.py, I selected chrome_undetected (For easy captcha)

Thanks

**Comment by AmmeySaini** [comment]
try removing all the files first and re clone the repo and run setup.py, also you can try choosing different browser (just checked with firefox, worked fine)

**Comment by p32929** [comment]
Tried recloning, resetuping and rerunning the project using firefox. but in firefox, it just stucks here and doesn't do anything. 
( waited more than 10 minutes but nothing happened )

![Screenshot (83)](https://user-images.githubusercontent.com/6418354/128028083-f869aa5e-1ee3-41bb-9959-3dbd183bee47.png)

**Comment by AyaanZaveri** [comment]
Same thing happens to me!

**Comment by p32929** [comment]
If its working in your PC, can you please just create me one edu mail address and send it to me? 
Thanks a million

**Comment by AmmeySaini** [comment]
It's weird to see such an error.
Are you on windows or linux ? (was tested on linux but should work for windows too) :/

**Comment by Thenafi** [comment]
if it's not working it's because of the IP. I tested in windows worked fine for me .....but first, I tried using a GitHub VPS..it failed there.. then I tried with google colab it failed too... then I tried in my own pc using VPN like windscribe and tikvpn it failed ... no matter what browser I choose it fails.......then I used a USA residential static IP and firefox its worked submitted perfectly...

**Comment by FeelsBadMan1** [comment]
I had that issure too. That means that they not only banned chromedriver but also your IP. Consider getting a virtual creditcard, open a amazon aws account then create a windows rdp there and use it on the rdp. works fine for me

**Comment by p32929** [comment]
I'm using Windows 10 @AmmeySaini

**Comment by AyaanZaveri** [comment]
It works now on Firefox for me now!

**Comment by AmmeySaini** [comment]
UPDATE - TESTED AND WORKING ON LINUX (FIREFOX, CHROME, UNDETECTED CHROME)
Windows - Needed to be tested

**Comment by p32929** [comment]
today I tried using a VPN (windscribe - USA IP ) and the page loaded. but it keeps on loading captchas and doesn't go further than that. thus it crashes, I guess because it cannot find the elements on the DOM.

**Comment by AmmeySaini** [comment]
What do you mean by keep loading captchas ?

**Comment by Thenafi** [comment]
> today I tried using a VPN (windscribe - USA IP ) and the page loaded. but it keeps on loading captchas and doesn't go further than that. thus it crashes, I guess because it cannot find the elements on the DOM.

Windscribe will not work... But get a residential static IP or AWS IP...

**Comment by Thenafi** [comment]
> What do you mean by keep loading captchas ?

When I used with vpn and or other blocked ip...the captcha for vpn and proxy keeps coming up again again ...i think server easily recognizes vpn services .. popular ones and block them

**Comment by p32929** [comment]
I was actually able to register in OpenCCC using Windscribe manually without using the script. So, now I'll have to wait 24-48 hours to login to the web portal. right?

**Comment by p32929** [comment]
I was actually able to register in OpenCCC using Windscribe manually without using the script. So, now I'll have to wait 24-48 hours to login to the web portal. right?
Here's a screenshot of the email. Is there anything else I have to do to get the edu email?
![Screenshot (86)](https://user-images.githubusercontent.com/6418354/128178399-339faa5d-b88c-4926-95db-4e29f686668c.png)

Thanks

**Comment by FeelsBadMan1** [comment]
Hello, anyone knows what emial college i should use for apply to the github students devpack? i currently have the one from consta costra college with the domain @insite.4cd.edu but github deny this email domain....

**Comment by FeelsBadMan1** [comment]
> 
> 
> I was actually able to register in OpenCCC using Windscribe manually without using the script. So, now I'll have to wait 24-48 hours to login to the web portal. right?
> Here's a screenshot of the email. Is there anything else I have to do to get the edu email?
> ![Screenshot (86)](https://user-images.githubusercontent.com/6418354/128178399-339faa5d-b88c-4926-95db-4e29f686668c.png)
> 
> Thanks

WHat is grossment college? this is no option on the bot....

**Comment by red0888** [comment]
> today I tried using a VPN (windscribe - USA IP ) and the page loaded. but it keeps on loading captchas and doesn't go further than that. thus it crashes, I guess because it cannot find the elements on the DOM.

Same thing, when using a VPN it shows captcha and you can't solve it at all, but it does not ask for captcha on own IP. Now I have to see some way to get a private USA proxy :/
