### ISSUE TITLE
Can't run program

### ISSUE THREAD

**Issue by StrawberryMilk9462** [AmmeySaini/Edu-Mail-Generator#91]
Hey thanks for the great project! Having some issues starting up however. I have python 3.9 installed and pip shows it is installed in cmd. I pressed the setup program and it says everything has been "satisfied" which is good. The helper.py program however just always closes when i try to open it so i went on to the actual bot to try to run it. At the beginning everything looks pretty good, i can enter which uni and my email address. After i enter my email address though i get to this :
![image](https://user-images.githubusercontent.com/81608720/128054114-3c4ec593-1135-4cc5-860d-6b6a636d6420.png)
and some code flashes by too quick for me to screenshot. The bot then closes itself everytime after i get to this step. Was hoping for help. I was thinking maybe i didn't do something correctly in the Update v0.2.7. I downloaded chrome/chromium but its just on a folder on my pc and i HAVE NOT touched it yet just downloaded it. Thank you!

**Comment by AmmeySaini** [comment]
If it closed unexpectedly there must be an error traceback, please share the full screenshot for detailed info on the error

**Comment by FeelsBadMan1** [comment]
> 
> 
> Hey thanks for the great project! Having some issues starting up however. I have python 3.9 installed and pip shows it is installed in cmd. I pressed the setup program and it says everything has been "satisfied" which is good. The helper.py program however just always closes when i try to open it so i went on to the actual bot to try to run it. At the beginning everything looks pretty good, i can enter which uni and my email address. After i enter my email address though i get to this :
> ![image](https://user-images.githubusercontent.com/81608720/128054114-3c4ec593-1135-4cc5-860d-6b6a636d6420.png)
> and some code flashes by too quick for me to screenshot. The bot then closes itself everytime after i get to this step. Was hoping for help. I was thinking maybe i didn't do something correctly in the Update v0.2.7. I downloaded chrome/chromium but its just on a folder on my pc and i HAVE NOT touched it yet just downloaded it. Thank you!

Please run the script in a cmd window and dont run it using doubbleclick. if you run it by open cmd and then drag & drop to pyfile into the cmd then hit enter you see the erroroutput without mcd closing direclty so you can let us know what exaclty the error is.

**Comment by StrawberryMilk9462** [comment]
I figured it out! The cmd drag wasn't working so i brought it into Visual Studio Code, and it turned out the setup.py file wasn't downloaded correctly  and i needed to redownload pip. All good now, thank you two so much!

**Comment by StrawberryMilk9462** [comment]
Some small issues now while running, is the program just stops filling in fields. I'll try to find a solution.

**Comment by StrawberryMilk9462** [comment]
bot seems to stop filling in info here alot
![image](https://user-images.githubusercontent.com/81608720/128217908-aedaff05-cfbf-4120-ad8f-e9f139bc8bed.png)

**Comment by AmmeySaini** [comment]
For how long it's stuck there ??
If it's in seconds then it's not any bug, just random sleep time
