### ISSUE TITLE
I got error: Firefox not detected whereas it is installed 

### ISSUE THREAD

**Issue by DavidGlovers** [AmmeySaini/Edu-Mail-Generator#95]
Hey,

I got this error:
Firefox
Firefox isn't installed

Chrome
Chrome isn't installed
Error - Setup installation failed
Reason - Please install either Chrome or Firefox browser to complete setup process

I have been using firefox for last many yrs and only use firefox and it works great nut when I ran the :
setup

it gave above error. It doesn't detect the firefox so what do I do:

I'm on Windows 10 64 bit
Firefox is also 64 bit installed in default location: C drive

Thanks in advance!

**Comment by DavidGlovers** [comment]
What do you mean by:
'Message that will be displayed on users first issue'

**Comment by FeelsBadMan1** [comment]
> 
> 
> What do you mean by:
> 'Message that will be displayed on users first issue'

This is the githubbot. the message will be sent on users that open their fist issure. just ignore it.
Regarding your issure after running the setup try chrome_undetected.

**Comment by AmmeySaini** [comment]
Try reinstalling firefox with default options
